name: Build and Push API Image

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - "PicHub.API/**" # trigger when API code changes

jobs:
  lint:
    name: Analyze .NET Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore Dependencies
        run: dotnet restore PicHub.API/PicHub.API.csproj

      - name: Run .NET Code Analysis
        run: dotnet build PicHub.API/PicHub.API.csproj --no-restore --configuration Release

  build_and_push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./PicHub.API
          file: ./PicHub.API/Dockerfile
          push: true
          tags: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/pichub/api:latest
