name: Terraform Infra Deployment

on:
  workflow_run:
    workflows: ["Build and Deploy API"]
    types:
      - completed

  push:
    branches:
      - master
    paths:
      - "infra/**" # run when tf code changes

jobs:
  deploy_infra:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.11.2"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Output Swagger UI URL
        run: |
          echo "API doc should be available at:"
          terraform output -raw swagger_ui_url
